pipeline {
    agent { docker { image 'openjdk:12' } }
    stages {
        stage('build') {
            steps {
                sh 'java -version'
                sh 'package'

            }
        }
    }
} 

