pipeline {
    agent { docker { image 'maven:3.8.1' } }
    stages {
        stage('build') {
            steps {
                sh 'mvn --version'
                sh 'mvn package'
            }
        }
        stage('test'){
            steps{
                sh 'mvn clean test'
            }
            post {
                always {
                   junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('test'){
            steps{
                sh 'mvn clean test'
            }
            post {
                always {
                          junit "**/build/test-results/*.xml"
                          step([
                              $class         : 'FindBugsPublisher',
                              pattern        : 'build/reports/findbugs/*.xml',
                              canRunOnFailed : true
                          ])
                          step([
                              $class         : 'PmdPublisher',
                              pattern        : 'build/reports/pmd/*.xml',
                              canRunOnFailed : true
                          ])
                          step([
                              $class           : 'JacocoPublisher',
                              execPattern      : 'build/jacoco/jacoco.exec',
                              classPattern     : 'build/classes/main',
                              sourcePattern    : 'src/main/java',
                              exclusionPattern : '**/*Test.class'
                          ])
                          publishHTML([
                              allowMissing          : false,
                              alwaysLinkToLastBuild : false,
                              keepAll               : true,
                              reportDir             : 'build/asciidoc/html5',
                              reportFiles           : 'index.html',
                              reportTitles          : "API Documentation",
                              reportName            : "API Documentation"
                          ])
                          sh "gradle clean"
                        }
            }
        }


    }
} 

